export const QUERY_KEY = {
  APP: "APP",
  ADMIN: "ADMIN",
  USER: "USER",
  APT: "APT",
  ACCOUNT: "ACCOUNT",
  AVIABLE_APARTMENT: "AVIABLE_APARTMENT",
  MY_APT: "MY_APT",
  MY_PROFILE: "MY_PROFILE",
  CONTACT: "CONTACT",
  CONTRACT: "CONTRACT",
  UTILITY: "UTILITY",
  INVOICE: 'INVOICE'
};
